export enum TypeRessource{
    SIROP="SIROP",
    POMMADES="POMMADES",
    DISPOSITIFS="DISPOSITIFS",
    PENSEMENTS="PENSEMENTS",
    DESINFECTANT="DESINFECTANT",
    VITAMINES="VITAMINES",
    MEDICAMENTS="MEDICAMENTS"
}